src/main/java/br/com/ideiasaleatorias/bolao/models/reports/ReportChampionshipResultView.java
package br.com.ideiasaleatorias.bolao.models.reports;

import br.com.ideiasaleatorias.bolao.models.ActualGameResult;
import br.com.ideiasaleatorias.bolao.models.Game;
import br.com.ideiasaleatorias.bolao.models.Team;
import br.com.ideiasaleatorias.bolao.models.scorerules.GameOutcome;

public class ReportChampionshipResultView {

	private ActualGameResult result;
	private Team teamAnalysed;

	public ReportChampionshipResultView(ActualGameResult result,Team teamAnalysed) {
		this.result = result;
		this.teamAnalysed = teamAnalysed;
	}

	public int getPrincipalScore() {
		return result.getPrincipalScore();
	}

	public int getVisitingScore() {
		return result.getVisitingScore();
	}

	public Game getGame() {
		return result.getGame();
	}
	
	/**
	 * 
	 * @return uma string representando o resultado do time sendo analisado
	 */
	public String getOutcome(){
		GameOutcome outcome = GameOutcome.discover(result);
		if(outcome.equals(GameOutcome.DRAW)){
			return "empate";
		}
		
		if(result.getGame().getPrincipalTeam().equals(teamAnalysed) && outcome.equals(GameOutcome.PRINCIPAL_WINNER)){
			return "vitoria";
		}
		
		if(result.getGame().getVisitingTeam().equals(teamAnalysed) && outcome.equals(GameOutcome.VISITING_WINNER)){
			return "vitoria";
		}
		
		return "derrota";
	}
	
	

}

src/main/java/br/com/ideiasaleatorias/bolao/controllers/ReportController.java
package br.com.ideiasaleatorias.bolao.controllers;

import java.util.List;
import java.util.stream.Collectors;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import br.com.ideiasaleatorias.bolao.controllers.forms.ReportChampionshipResultForm;
import br.com.ideiasaleatorias.bolao.daos.ActualGameResultDao;
import br.com.ideiasaleatorias.bolao.daos.ChampionshipDao;
import br.com.ideiasaleatorias.bolao.daos.GameDao;
import br.com.ideiasaleatorias.bolao.daos.GameGuessDao;
import br.com.ideiasaleatorias.bolao.daos.TeamDao;
import br.com.ideiasaleatorias.bolao.exceptions.NotFoundException;
import br.com.ideiasaleatorias.bolao.models.ActualGameResult;
import br.com.ideiasaleatorias.bolao.models.Game;
import br.com.ideiasaleatorias.bolao.models.GameGuess;
import br.com.ideiasaleatorias.bolao.models.Team;
import br.com.ideiasaleatorias.bolao.models.reports.ReportChampionshipResultView;

@Controller
public class ReportController {

	@Autowired
	private ChampionshipDao championshipDao;
	@Autowired
	private TeamDao teamDao;
	@Autowired
	private ActualGameResultDao actualGameResultDao;
	@Autowired
	private GameDao gameDao;
	@Autowired
	private GameGuessDao gameGuessDao;
	
	@GetMapping("/report/championship/results/form")
	public String resultsForm(Model model, ReportChampionshipResultForm form) {
		model.addAttribute("championshipList", championshipDao.findAll());
		if (form.hasChampionship()) {
			model.addAttribute("teamList",
					teamDao.findAllByChampionshipOrderByNameAsc(form.getChampionshipId()));
		}
		return "/reports/championship-results";
	}

	@GetMapping("/report/championship/results")
	public String resultByTeam(Model model, @Valid ReportChampionshipResultForm form,
			BindingResult bindingResult, RedirectAttributes redirectAttributes) {
		if (bindingResult.hasErrors()) {
			return resultsForm(model, form);
		}

		List<ActualGameResult> results = actualGameResultDao
				.findAllByChampionshipAndTeam(form.getChampionshipId(), form.getTeamId());
		Team team = teamDao.findOne(form.getTeamId());
		model.addAttribute("resultList",
				results.stream().map(result -> {
					return new ReportChampionshipResultView(result,team);
				}).collect(Collectors.toList()));

		return resultsForm(model, form);
	}
	
	@GetMapping("/report/guesses/game/{gameId}")
	public String guessePerGame(Model model, @PathVariable("gameId") Integer gameId) {
		Game game = gameDao.findOne(gameId);
		if(game.allowGuess()) {
			throw new NotFoundException("Você procura por algo que ainda não está disponível :P");
		}
		
		model.addAttribute("guesses",gameGuessDao.findAllByGameId(game.getId()));
		model.addAttribute("game", game);
		
		return "/reports/guesses-per-game";
	}
}

src/main/webapp/WEB-INF/views/reports/championship-results.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib tagdir="/WEB-INF/tags/" prefix="bolao"%>
<%@include file="../../taglibs.jsp"%>
<bolao:masterPage title="Ranking do grupo">
	<jsp:attribute name="extraCss">
		<link href="/assets/js/jquery/multiple-select/css/multi-select.css" media="screen" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,300,600" type="text/css">
		<link rel="stylesheet" href="/assets/css/fonts.css" />
		<link rel="stylesheet" href="/assets/css/projection.css" />
	</jsp:attribute>
	<jsp:attribute name="extraScripts">
		<script src="/assets/js/jquery/jquery.chained.remote.min.js"></script>
		<script>
			$("#teamId").remoteChained({
	    		parents : "#championshipId",
	    		url : "/ajax/championship/teams",
	    		loading: "Carregando times",
	    		attribute: "data-param"
			});			
		</script>	
	</jsp:attribute>
	<jsp:body>
		<div class="box">
			<div class="box-header" style="text-align: center">
				<h2>Pesquise o histórico do time</h2>
			</div>
		</div>
		<div class="box" style="text-align: center">
			<form:form action="/report/championship/results" method="get" commandName="reportChampionshipResultForm">
				<div class="row">
					<div class="col-xs-6 text-right">
						<label for="championshipId">Campeonato</label>
						</div>
					<div class="col-xs-6 text-left">
						<form:select path="championshipId" data-param="id">
							<form:option value="">--Selecione--</form:option>
							<form:options items="${championshipList}" itemLabel="name" itemValue="id"/>							
						</form:select>
						<form:errors path="championshipId" cssClass="error_message"/>
					</div>
				</div>

				<div class="row">
					<div class="col-xs-6 text-right">
						<label for="bestDefenseTeamId">Times</label>
					</div>
					<div class="col-xs-6 text-left">
						<form:select path="teamId" id="teamId" items="${teamList}" itemLabel="name" itemValue="id"/>
						<form:errors path="teamId" cssClass="error_message"/>
					</div>
				</div>

				<div class="row" style="margin:5px">
					<button type="submit" class="btn">Pesquisar"</button> 
				</div>
			</form:form>				
		</div>
					
		<div class="box-body table-responsive no-padding"  style="text-align: center">
			<table class="table table-hover">
				<tbody>
					<tr>
						<th style="text-align: center">Rodada</th>
						<th style="text-align: center">Jogo</th>
						<th style="text-align: center">Resultado</th>
						<th style="text-align: center">Placar</th>
					</tr>
					<c:forEach var="result" items="${resultList}">
						<tr>
							<td>${result.game.round}</td>
							<td>${result.game.principalTeam.name}x${result.game.visitingTeam.name}</td>
							<td>${result.outcome}</td>
							<td>${result.principalScore}x${result.visitingScore}</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</div>
</jsp:body>
</bolao:masterPage>

src/main/webapp/WEB-INF/views/reports/guesses-per-game.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib tagdir="/WEB-INF/tags/" prefix="bolao"%>
<%@include file="../../taglibs.jsp"%>

<bolao:masterPage title="Auditoria">
	<div class="box">
		<div class="box-header"  style="text-align: center">
			<h3 class="box-title">${game.principalTeam.name} x ${game.visitingTeam.name}</h3>
		</div>		
		<div class="box-body table-responsive no-padding">
			<table class="table table-hover table-striped dataTable" role="grid">
				<tbody>
					<tr style="text-align: center">
						<td>Palpite</td>
						<td>Participante</td>
						<td>Dobrado</td>
						<td>Horário</td>
					</tr>
					<c:forEach items="${guesses}" var="guess">
						<tr style="text-align: center">
							<td>${guess.principalScore} x ${guess.visitingScore}</td>
							<td>${guess.member.systemUser.name}</td>
							<td>${guess.doubled ? 'Sim' : 'Não'}</td>
							<td>${dateFormatter.format(guess.time)}</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</div>
	</div>
</bolao:masterPage>

src/main/webapp/WEB-INF/views/reports/list-start-guesses.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib tagdir="/WEB-INF/tags/" prefix="bolao"%>
<%@include file="../../taglibs.jsp"%>

<bolao:masterPage title="Palpites iniciais">
	<div class="box">
		<div class="box-header"  style="text-align: center">
			<h3 class="box-title">Todos os palpites iniciais</h3>
		</div>		
		<div class="box-body table-responsive no-padding">
			<table class="table table-hover table-striped dataTable" role="grid">
				<tbody>
					<tr style="text-align: center">
						<td>Palpite</td>
						<td>Participante</td>
						<td>Dobrado</td>
						<td>Horário</td>
					</tr>
					<c:forEach items="${guesses}" var="guess">
						<tr style="text-align: center">
							<td>${guess.principalScore} x ${guess.visitingScore}</td>
							<td>${guess.member.systemUser.name}</td>
							<td>${guess.doubled ? 'Sim' : 'Não'}</td>
							<td>${dateFormatter.format(guess.time)}</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</div>
	</div>
</bolao:masterPage>